spring:
  devtools:
    add-properties: false
  banner:
    image:
      bitdepth: 8
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: patrick
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
server:
  port: 8081

springdoc:
  swagger-ui:
    path: "/"

