spring:
  devtools:
    add-properties: false
  banner:
    image:
      bitdepth: 8
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    username:
    password: patrick
server:
  port: 8081

